services:
  db:
    image: mysql:8.0
    container_name: hospital-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
    volumes:
      - mysql_data:/var/lib/mysql   # ← persistent MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    # (optional) expose DB to host tools like Workbench/DBeaver:
    # ports:
    #   - "3307:3306"               # host:container

  backend:
    build: .
    container_name: hospital-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hospital
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mysql_data: {}
